version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: navops-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - navops-pgdata:/var/lib/postgresql/data
      # Instanciación automática del script SQL
      - "./data base/navops.sql:/docker-entrypoint-initdb.d/navops.sql"
      - "./backend/src/main/resources/db/migration:/docker-entrypoint-initdb.d/"
    restart: always

  navops-api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: navops-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      #Servicio de PostgreSQL
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}

      # JWT Security
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}

      #Servicio de Claudinary
      - CLOUDINARY_NAME=${CLOUDINARY_NAME}
      - CLOUDINARY_KEY=${CLOUDINARY_KEY}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}

      #Servicio de MSPT
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}

      #Servicio de JWT
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}


volumes:
  navops-pgdata:

