ALTER TABLE ships
    ADD COLUMN IF NOT EXISTS status      VARCHAR(50) NOT NULL DEFAULT 'OPERATIONAL',
    ADD COLUMN IF NOT EXISTS hull_number VARCHAR(100),
    ADD COLUMN IF NOT EXISTS hold_count  SMALLINT,
    ADD COLUMN IF NOT EXISTS is_active   BOOLEAN NOT NULL DEFAULT true;

ALTER TABLE engines
    ADD COLUMN IF NOT EXISTS serial_number         VARCHAR(100),
    ADD COLUMN IF NOT EXISTS last_tbo_engine_hours INTEGER;
